export const MARKETPLACE_SKILLS = [
  {
    id: "skl-rover-drift-v2",
    name: "Rover Drift Compensator v2",
    author: "@axl_engineering",
    description:
      "Compensates for wheel slip in low-cohesion regolith. Cuts off-route drift by 80% on slopes >12°.",
    compatibleRoles: ["CONSTRUCTOR", "SURVEYOR", "MINER"],
    downloadCount: 4218,
    rating: 4.7,
    priceCredits: 250,
    verified: true,
    category: "NAVIGATION" as const,
  },
  {
    id: "skl-vein-finder",
    name: "Vein Finder (Hematite/Olivine)",
    author: "@regolith_jpg",
    description:
      "Spectrometer post-processor for hematite, olivine, and high-priority extraction indicators.",
    compatibleRoles: ["MINER", "SURVEYOR"],
    downloadCount: 1903,
    rating: 4.4,
    priceCredits: 180,
    verified: true,
    category: "MINING" as const,
  },
  {
    id: "skl-storm-shelter",
    name: "Storm Shelter Auto-Park",
    author: "@dust_devil_dev",
    description:
      "Detects opacity tau spikes and parks the bot leeward of nearest terrain feature. Saves your panels.",
    compatibleRoles: ["CONSTRUCTOR", "SURVEYOR", "MINER", "MEDIC", "RELAY"],
    downloadCount: 11240,
    rating: 4.9,
    priceCredits: 0,
    verified: true,
    category: "SAFETY" as const,
  },
  {
    id: "skl-relay-mesh",
    name: "Mesh Relay Handshake",
    author: "@uplink_betty",
    description:
      "Three-asset mesh networking protocol with alternate routing during link degradation.",
    compatibleRoles: ["RELAY", "SURVEYOR"],
    downloadCount: 762,
    rating: 4.2,
    priceCredits: 320,
    verified: false,
    category: "COMMS" as const,
  },
  {
    id: "skl-medbot-triage",
    name: "MedBot Triage Protocol",
    author: "@vital_signs",
    description:
      "Prioritizes diagnostic ports across a fleet. Spots the bot most likely to fail next sol.",
    compatibleRoles: ["MEDIC"],
    downloadCount: 488,
    rating: 4.6,
    priceCredits: 410,
    verified: true,
    category: "REPAIR" as const,
  },
  {
    id: "skl-survey-grid",
    name: "Adaptive Survey Grid",
    author: "@cartographer.exe",
    description:
      "Replaces canned grid sweeps with adaptive pathing. Skips dead zones, doubles down on anomalies.",
    compatibleRoles: ["SURVEYOR"],
    downloadCount: 2671,
    rating: 4.5,
    priceCredits: 220,
    verified: true,
    category: "SURVEY" as const,
  },
  {
    id: "skl-thermal-blanket",
    name: "Pre-Dawn Thermal Blanket",
    author: "@coldsnap",
    description:
      "Uses controlled overnight power draw to keep electronics above survival threshold.",
    compatibleRoles: ["CONSTRUCTOR", "MINER", "MEDIC"],
    downloadCount: 5519,
    rating: 4.8,
    priceCredits: 90,
    verified: true,
    category: "SAFETY" as const,
  },
  {
    id: "skl-jolt-impact",
    name: "Jolt Impact Profile",
    author: "@hammertime",
    description:
      "Impact-driver torque profile for cold-soaked rock and reduced bit failure.",
    compatibleRoles: ["CONSTRUCTOR", "MINER"],
    downloadCount: 1342,
    rating: 4.3,
    priceCredits: 140,
    verified: false,
    category: "MINING" as const,
  },
];
